apiVersion: v1
kind: Service
metadata:
  name: fastapi-ml-service
spec:
  type: LoadBalancer
  selector:
    app: fastapi-ml-app
  ports:
    - name: http
      protocol: TCP
      port: 8080            # external service port
      targetPort: 8000 
      nodePort: 3000   # container port
    
    